### ISSUE TITLE
Kitty readme links to tmux

### ISSUE THREAD

**Issue by joeyjurjens** [sspaeti/dotfiles#1]
I Just read your "Why Vim Is More than Just an Editor – Vim Language, Motions, and Modes Explained" article, nicely written!
You linked this repo and thought i'd let you know that the kitty terminal link in your README.md links to the tmux wiki.

**Comment by sspaeti** [comment]
Hey Joe, thanks so much for the kind hint; it is much appreciated. I fixed it. And happy you liked the article 🙌🏻😍.
